package com.mfix.pos;

import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;

/** Runtime backup/restore layer. Export is JSON; restore validates before replacing app state. */
public class BackupRestorePatchActivity extends UsersPermissionsPatchActivity {
    private static final String PATCH =
        "(function(){if(window.__mfixBackupPatch)return;window.__mfixBackupPatch=true;"+
        "function install(){if(!window.STATE||typeof window.openModal!=='function'){setTimeout(install,250);return;}"+
        "window.mfixOpenBackupRestore=function(){var html='<div class=\\\"modal\\\"><div class=\\\"modal-head\\\"><h3>💾 גיבוי ושחזור</h3><button class=\\\"modal-close\\\" onclick=\\\"closeModal()\\\">✕</button></div><div class=\\\"modal-body\\\"><div class=\\\"card\\\"><b>גיבוי מלא</b><div class=\\\"muted\\\">מוצרים, מלאי, לקוחות, מכירות, הגדרות והיסטוריה לקובץ JSON.</div><button class=\\\"btn btn-primary\\\" style=\\\"margin-top:10px\\\" onclick=\\\"mfixExportBackup()\\\">ייצוא גיבוי</button></div><div class=\\\"card\\\" style=\\\"margin-top:12px\\\"><b>שחזור</b><div class=\\\"muted\\\">השחזור מחליף את הנתונים הקיימים לאחר אישור.</div><input id=\\\"mfixBackupFile\\\" class=\\\"input\\\" type=\\\"file\\\" accept=\\\"application/json,.json\\\" style=\\\"margin-top:10px\\\"><button class=\\\"btn btn-red\\\" style=\\\"margin-top:10px\\\" onclick=\\\"mfixRestoreBackup()\\\">שחזר מגיבוי</button></div></div></div>';openModal(html);};"+
        "window.mfixExportBackup=function(){var payload={format:'MFIX_POS_BACKUP',version:2,createdAt:new Date().toISOString(),state:window.STATE,users:localStorage.getItem('mfix_pos_users_v1'),activeUser:localStorage.getItem('mfix_pos_active_user_v1'),yeshInvoice:localStorage.getItem('mfix_yesh_invoice_v1'),yeshInvoiceOutbox:localStorage.getItem('mfix_yesh_invoice_outbox_v1')};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mfix-pos-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);toast('הגיבוי יוצא לקובץ','ok');};"+
        "window.mfixRestoreBackup=function(){var f=document.getElementById('mfixBackupFile').files[0];if(!f){toast('יש לבחור קובץ גיבוי','err');return;}var r=new FileReader();r.onload=function(){try{var b=JSON.parse(r.result);if(!b||b.format!=='MFIX_POS_BACKUP'||!b.state||typeof b.state!=='object')throw new Error('invalid');if(!confirm('השחזור יחליף את כל הנתונים הקיימים. להמשיך?'))return;Object.keys(window.STATE).forEach(function(k){delete window.STATE[k];});Object.assign(window.STATE,b.state);if(b.users!=null)localStorage.setItem('mfix_pos_users_v1',b.users);if(b.activeUser!=null)localStorage.setItem('mfix_pos_active_user_v1',b.activeUser);if(b.yeshInvoice!=null)localStorage.setItem('mfix_yesh_invoice_v1',b.yeshInvoice);if(b.yeshInvoiceOutbox!=null)localStorage.setItem('mfix_yesh_invoice_outbox_v1',b.yeshInvoiceOutbox);try{localStorage.setItem('mfix_pos_state',JSON.stringify(window.STATE));}catch(e){}toast('השחזור הושלם. האפליקציה תיטען מחדש','ok');setTimeout(function(){location.reload();},700);}catch(e){toast('קובץ הגיבוי אינו תקין או אינו בפורמט MFIX POS','err');}};r.readAsText(f);};"+
        "function inject(){var host=document.querySelector('.topbar-right'),b=document.getElementById('mfixBackupButton');if(host&&!b){b=document.createElement('button');b.id='mfixBackupButton';b.className='btn btn-outline';b.textContent='💾 גיבוי';b.onclick=window.mfixOpenBackupRestore;host.appendChild(b);}}inject();setInterval(inject,1000);console.log('[MFIX] backup restore patch active');}"+
        "install();})();";
    @Override protected void onCreate(Bundle savedInstanceState){super.onCreate(savedInstanceState);View root=((ViewGroup)findViewById(android.R.id.content)).getChildAt(0);if(root instanceof WebView)((WebView)root).postDelayed(()->((WebView)root).evaluateJavascript(PATCH,null),1800);}
}
