package com.mfix.pos;

import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;

/** Runtime backup/restore layer. Restore validates the file and persists through the app's real storage API. */
public class BackupRestorePatchActivity extends UsersPermissionsPatchActivity {
    private static final String PATCH =
        "(function(){if(window.__mfixBackupPatch)return;window.__mfixBackupPatch=true;"+
        "function install(){if(!window.STATE||typeof window.openModal!=='function'){setTimeout(install,250);return;}"+
        "function summary(s){s=s||{};return 'מוצרים: '+(Array.isArray(s.products)?s.products.length:0)+' | לקוחות: '+(Array.isArray(s.customers)?s.customers.length:0)+' | מכירות: '+(Array.isArray(s.sales)?s.sales.length:0)+' | תיקונים: '+(Array.isArray(s.repairs)?s.repairs.length:0);}"+
        "function validState(s){return !!s&&typeof s==='object'&&!Array.isArray(s)&&s.settings&&typeof s.settings==='object'&&!Array.isArray(s.settings)&&['products','customers','sales','repairs'].every(function(k){return Array.isArray(s[k]);});}"+
        "function normalizeBackup(b){if(!b||typeof b!=='object')throw new Error('invalid');var st=b.state;if(!st&&b.format==='MFIX-POS-BACKUP'){st={settings:b.settings,products:b.products,customers:b.customers,sales:b.sales,repairs:b.repairs,returns:b.returns||[],shifts:b.shifts||[],giftCards:b.giftCards||[],preorders:b.preorders||[],auditLog:b.auditLog||[],inventoryHistory:b.inventoryHistory||[],currentShift:b.currentShift||null};}if(!(b.format==='MFIX_POS_BACKUP'||b.format==='MFIX-POS-BACKUP')||!validState(st))throw new Error('invalid');return {state:st,createdAt:b.createdAt||b.exportedAt||'',summary:b.summary||summary(st),users:b.users,activeUser:b.activeUser,yeshInvoice:b.yeshInvoice,yeshInvoiceOutbox:b.yeshInvoiceOutbox};}"+
        "async function persistRestoredState(st){if(typeof window.saveKey!=='function')throw new Error('מנגנון שמירת הנתונים אינו זמין');var misc={returns:Array.isArray(st.returns)?st.returns:[],shifts:Array.isArray(st.shifts)?st.shifts:[],giftCards:Array.isArray(st.giftCards)?st.giftCards:[],preorders:Array.isArray(st.preorders)?st.preorders:[],auditLog:Array.isArray(st.auditLog)?st.auditLog:[],inventoryHistory:Array.isArray(st.inventoryHistory)?st.inventoryHistory:[]};await window.saveKey('cp_settings',st.settings);await window.saveKey('cp_products',st.products);await window.saveKey('cp_customers',st.customers);await window.saveKey('cp_sales',st.sales);await window.saveKey('cp_repairs',st.repairs);await window.saveKey('cp_misc',misc);}"+
        "async function readBackupText(text){try{var b=normalizeBackup(JSON.parse(text)),st=b.state;var info=(b.createdAt?('תאריך גיבוי: '+new Date(b.createdAt).toLocaleString('he-IL')+'\\n'):'')+(b.summary||summary(st))+'\\n\\nהשחזור יחליף את כל הנתונים הקיימים. להמשיך?';if(!confirm(info))return;var old=window.STATE;var next=Object.assign({},st,{cart:[],cartCustomerId:null,linkedRepairId:null,docCustomerName:'',docCustomerPhone:'',pointsToRedeem:0,loaded:true});await persistRestoredState(st);Object.keys(old).forEach(function(k){delete old[k];});Object.assign(old,next);if(b.users!=null)localStorage.setItem('mfix_pos_users_v1',b.users);if(b.activeUser!=null)localStorage.setItem('mfix_pos_active_user_v1',b.activeUser);if(b.yeshInvoice!=null)localStorage.setItem('mfix_yesh_invoice_v1',b.yeshInvoice);if(b.yeshInvoiceOutbox!=null)localStorage.setItem('mfix_yesh_invoice_outbox_v1',b.yeshInvoiceOutbox);if(typeof window.render==='function')window.render();toast('השחזור הושלם ונשמר במאגר הנתונים','ok');setTimeout(function(){location.reload();},700);}catch(e){console.error('[MFIX BACKUP RESTORE]',e);toast('השחזור נכשל: '+(e&&e.message?e.message:'קובץ גיבוי לא תקין'),'err');}}window.mfixReceiveNativeBackup=function(b64){try{var bin=atob(b64),bytes=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);readBackupText(new TextDecoder().decode(bytes));}catch(e){console.error(e);toast('לא ניתן לקרוא את קובץ הגיבוי','err');}};"+
        "function nativeSave(filename,text){if(!(window.AndroidPrinter&&typeof AndroidPrinter.saveTextFile==='function'))return false;try{var bytes=new TextEncoder().encode(text),bin='';for(var i=0;i<bytes.length;i++)bin+=String.fromCharCode(bytes[i]);AndroidPrinter.saveTextFile(filename,btoa(bin));return true;}catch(e){console.error(e);return false;}}"+
        "window.mfixOpenBackupRestore=function(){var html='<div class=\\\"modal\\\"><div class=\\\"modal-head\\\"><h3>💾 גיבוי ושחזור</h3><button class=\\\"modal-close\\\" onclick=\\\"closeModal()\\\">✕</button></div><div class=\\\"modal-body\\\"><div class=\\\"card\\\"><b>גיבוי מלא</b><div class=\\\"muted\\\">מוצרים, מלאי, לקוחות, מכירות, הגדרות והיסטוריה לקובץ JSON.</div><button class=\\\"btn btn-primary\\\" style=\\\"margin-top:10px\\\" onclick=\\\"mfixExportBackup()\\\">ייצוא גיבוי</button></div><div class=\\\"card\\\" style=\\\"margin-top:12px\\\"><b>שחזור</b><div class=\\\"muted\\\">תומך בגיבוי שנוצר מהמערכת ובגיבוי MFIX.</div><input id=\\\"mfixBackupFile\\\" class=\\\"input\\\" type=\\\"file\\\" accept=\\\"application/json,.json\\\" style=\\\"margin-top:10px\\\"><button class=\\\"btn btn-red\\\" style=\\\"margin-top:10px\\\" onclick=\\\"mfixRestoreBackup()\\\">בדוק ושחזר מגיבוי</button></div></div></div>';openModal(html);};"+
        "window.mfixExportBackup=function(){var payload={format:'MFIX_POS_BACKUP',version:3,createdAt:new Date().toISOString(),summary:summary(window.STATE),state:window.STATE,users:localStorage.getItem('mfix_pos_users_v1'),activeUser:localStorage.getItem('mfix_pos_active_user_v1'),yeshInvoice:localStorage.getItem('mfix_yesh_invoice_v1'),yeshInvoiceOutbox:localStorage.getItem('mfix_yesh_invoice_outbox_v1')},json=JSON.stringify(payload,null,2),filename='mfix-pos-backup-'+new Date().toISOString().slice(0,10)+'.json';if(nativeSave(filename,json)){toast('בחר מיקום לשמירת הגיבוי — '+payload.summary,'ok');return;}var blob=new Blob([json],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);toast('הגיבוי יוצא לקובץ — '+payload.summary,'ok');};"+
        "window.mfixRestoreBackup=function(){if(window.AndroidPrinter&&typeof AndroidPrinter.pickBackupFile==='function'){AndroidPrinter.pickBackupFile();return;}var input=document.getElementById('mfixBackupFile'),f=input&&input.files&&input.files[0];if(!f){toast('יש לבחור קובץ גיבוי','err');return;}if(f.size>50*1024*1024){toast('קובץ הגיבוי גדול מדי (מקסימום 50MB)','err');return;}var r=new FileReader();r.onerror=function(){toast('לא ניתן לקרוא את קובץ הגיבוי','err');};r.onload=function(){readBackupText(r.result);};r.readAsText(f);};"+
        "function inject(){var host=document.querySelector('.topbar-right'),b=document.getElementById('mfixBackupButton');if(host&&!b){b=document.createElement('button');b.id='mfixBackupButton';b.className='btn btn-outline';b.textContent='💾 גיבוי';b.onclick=window.mfixOpenBackupRestore;host.appendChild(b);}}inject();setInterval(inject,1000);console.log('[MFIX] backup restore patch active');}"+
        "install();})();";
    @Override protected void onCreate(Bundle savedInstanceState){super.onCreate(savedInstanceState);View root=((ViewGroup)findViewById(android.R.id.content)).getChildAt(0);if(root instanceof WebView)((WebView)root).postDelayed(()->((WebView)root).evaluateJavascript(PATCH,null),1800);}
}
