package com.mfix.pos;

import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;

/** Completes a paid POS sale, records it, and commits inventory movement. */
public class CheckoutCompletionPatchActivity extends PaymentManagementPatchActivity {
    private static final String PATCH =
        "(function(){" +
        "if(window.__mfixCheckoutCompletionPatch)return;window.__mfixCheckoutCompletionPatch=true;" +
        "function money(n){return Number(n||0).toLocaleString('he-IL',{minimumFractionDigits:2,maximumFractionDigits:2});}" +
        "function total(){try{if(typeof window.computeCartCalc==='function'){var c=window.computeCartCalc();return Number(c.totalIncl||c.total||0);}}catch(e){}return(window.STATE&&Array.isArray(window.STATE.cart)?window.STATE.cart:[]).reduce(function(s,x){return s+Number(x.lineTotal||x.total||((Number(x.price)||Number(x.unitPrice)||0)*(Number(x.qty)||1))||0);},0);}" +
        "function printerSettings(){try{var s=JSON.parse(localStorage.getItem('mfix_printer_settings_v1')||'{}');return {autoPrint:s.autoPrint!==false,footer:String(s.footer||''),storeName:String(s.storeName||''),storePhone:String(s.storePhone||''),storeAddress:String(s.storeAddress||''),receiptTitle:String(s.receiptTitle||'')};}catch(e){return {autoPrint:true,footer:'',storeName:'',storePhone:'',storeAddress:'',receiptTitle:''};}}" +
        "function selectedPrinter(){try{var id=(document.getElementById('st_defaultprinter')||{}).value||localStorage.getItem('mfix_default_printer_v1')||'';var ps=JSON.parse(AndroidPrinter.listUsbPrinters()||'[]');return ps.find(function(p){return p.id===id||p.name===id;})||ps[0]||null;}catch(e){return null;}}" +
        "function b64(s){try{return btoa(unescape(encodeURIComponent(s)));}catch(e){return '';}}" +
        "function receipt(sale){var cfg=printerSettings(),lines=[];if(cfg.storeName)lines.push(cfg.storeName);if(cfg.receiptTitle)lines.push(cfg.receiptTitle);if(cfg.storePhone)lines.push(cfg.storePhone);if(cfg.storeAddress)lines.push(cfg.storeAddress);lines.push('------------------------------','SALE '+sale.id);(sale.items||[]).forEach(function(i){var n=String(i.name||i.productName||i.sku||'item').slice(0,28),q=Number(i.qty||1),u=Number(i.price||i.unitPrice||0);lines.push(n+' x'+q+' '+money(q*u));});lines.push('------------------------------','TOTAL '+money(sale.total)+' NIS','PAID '+money(sale.payment.paid)+' NIS','METHOD '+String(sale.payment.method||'').toUpperCase());if(Array.isArray(sale.payment.parts))sale.payment.parts.forEach(function(x){lines.push('  '+String(x.method||'').toUpperCase()+': '+money(x.amount));});lines.push('CHANGE '+money(sale.payment.change)+' NIS','------------------------------','Thank you!');if(cfg.footer)lines.push(cfg.footer);lines.push('\\n\\n');return b64('\\x1b@'+lines.join('\\n')+'\\x1dV\\x00');}" +
        "function qty(x){return Math.max(1,Number(x.qty||1));}" +
        "function productId(x){return String(x.productId||x.id||x.sku||x.barcode||'');}" +
        "function serialsFor(item,p){var a=[];if(Array.isArray(item.imeis))a=a.concat(item.imeis);if(Array.isArray(item.serials))a=a.concat(item.serials);if(item.imei)a.push(item.imei);if(item.serial)a.push(item.serial);if(!a.length&&p&&Array.isArray(p.imeis))a=p.imeis.filter(function(x){return x.status==='available';}).slice(0,qty(item)).map(function(x){return x.value||x.imei||x.serial||x;});return a.map(function(x){return String(x&&x.value||x&&x.imei||x&&x.serial||x).trim();}).filter(Boolean);}" +
        "function commitInventory(cart){if(!window.STATE||!Array.isArray(window.STATE.products))return true;var changes=[];for(var i=0;i<cart.length;i++){var item=cart[i],id=productId(item),p=window.STATE.products.find(function(z){return String(z.id||z.sku||z.barcode||'')===id||String(z.sku||'')===String(item.sku||'')||String(z.barcode||'')===String(item.barcode||'');});if(!p)continue;var q=qty(item),before=Number(p.stock||0),serials=serialsFor(item,p),tracked=!!p.trackSerial||Array.isArray(p.imeis)||Array.isArray(p.serials);if(tracked&&serials.length<q){toast('יש לבחור '+q+' IMEI/מספרים סידוריים עבור '+(p.name||item.name||id),'err');return false;}if(!tracked&&Number.isFinite(before)&&before>=0&&before<q){toast('אין מספיק מלאי עבור '+(p.name||item.name||id),'err');return false;}changes.push({p:p,q:q,before:before,serials:serials,tracked:tracked});}if(!Array.isArray(window.STATE.inventoryHistory))window.STATE.inventoryHistory=[];changes.forEach(function(c){var after=c.tracked?Math.max(0,(Array.isArray(c.p.imeis)?c.p.imeis.filter(function(x){return x.status==='available';}).length:c.before)-c.q):Math.max(0,c.before-c.q);if(c.tracked&&Array.isArray(c.p.imeis)){var used=c.serials.slice(0,c.q);c.p.imeis.forEach(function(x){var v=String(x&&x.value||x&&x.imei||x&&x.serial||x);if(used.indexOf(v)>=0)x.status='sold';});c.p.stock=after;}else c.p.stock=after;window.STATE.inventoryHistory.unshift({id:'invh_'+Date.now()+'_'+Math.random().toString(36).slice(2),productId:c.p.id,type:'sale',qty:c.q,before:c.before,after:after,serials:c.serials.slice(0,c.q),reason:'מכירה',saleId:window.__mfixPendingSaleId||'',at:new Date().toISOString()});});try{if(typeof saveKey==='function'){saveKey('products',STATE.products);saveKey('misc',{returns:STATE.returns,shifts:STATE.shifts,giftCards:STATE.giftCards,preorders:STATE.preorders,auditLog:STATE.auditLog,inventoryHistory:STATE.inventoryHistory});}}catch(e){console.error(e);}return true;}" +
        "function finish(){var cart=window.STATE&&Array.isArray(window.STATE.cart)?window.STATE.cart:[];if(!cart.length){toast('הסל ריק — אין מה לסיים','err');return;}var t=total();var p=(window.STATE&&window.STATE.currentPayment)||null;if(!p||Number(p.remaining||Math.max(0,t-Number(p.paid||0)))>0){toast('יש להשלים תשלום לפני סיום המכירה','err');return;}var sale={id:'S'+Date.now(),at:new Date().toISOString(),total:Math.round(t*100)/100,items:cart.map(function(x){return JSON.parse(JSON.stringify(x));}),customer:(window.STATE&&window.STATE.customer)||null,payment:JSON.parse(JSON.stringify(p))};window.__mfixPendingSaleId=sale.id;if(!commitInventory(cart)){window.__mfixPendingSaleId='';return;}var sales=[];try{sales=JSON.parse(localStorage.getItem('mfix_completed_sales_v1')||'[]');if(!Array.isArray(sales))sales=[];}catch(e){}sales.push(sale);try{localStorage.setItem('mfix_completed_sales_v1',JSON.stringify(sales));localStorage.removeItem('mfix_current_payment_v1');}catch(e){}var cfg=printerSettings(),pr=cfg.autoPrint?selectedPrinter():null;if(pr&&p){try{var raw=receipt(sale);if(raw&&AndroidPrinter.printEscPosToDevice)AndroidPrinter.printEscPosToDevice(pr.id||pr.name,raw);}catch(e){console.log('[MFIX] receipt print failed',e);}}try{if(typeof window.mfixOnSaleCompleted==='function')window.mfixOnSaleCompleted(sale);}catch(e){console.error('[MFIX] sale completion callback failed',e);}window.__mfixPendingSaleId='';window.STATE.cart=[];window.STATE.currentPayment=null;try{if(typeof window.render==='function')window.render();}catch(e){}if(window.closeModal)window.closeModal();toast('המכירה '+sale.id+' הושלמה בהצלחה','ok');}" +
        "function install(){var v=document.getElementById('view-pos');if(!v){setTimeout(install,500);return;}if(v.querySelector('.mfix-finish-sale'))return;var b=document.createElement('button');b.type='button';b.className='btn btn-primary btn-lg mfix-finish-sale';b.textContent='✅ סיום מכירה';b.style.margin='0 0 10px 10px';b.onclick=finish;var host=v.querySelector('#cartTotals')||v;host.insertBefore(b,host.firstChild);}" +
        "install();console.log('[MFIX] checkout completion patch active');" +
        "})();";

    @Override protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        View root=((ViewGroup)findViewById(android.R.id.content)).getChildAt(0);
        if(root instanceof WebView)((WebView)root).postDelayed(()->((WebView)root).evaluateJavascript(PATCH,null),1700);
    }
}
