package com.mfix.pos;

import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;

/** Adds practical reports export and POS hold/resume controls to the existing WebView UI. */
public class ReportsExportPatchActivity extends InventoryManagementPatchActivity {
    private static final String PATCH =
        "(function(){" +
        "if(window.__mfixReportsExportPatch)return;window.__mfixReportsExportPatch=true;" +
        "function escCsv(v){v=String(v==null?'':v);return '\"'+v.replace(/\"/g,'\"\"')+'\"';}" +
        "function installReports(){" +
        "if(!window.STATE||typeof window.renderReports!=='function'){setTimeout(installReports,250);return;}" +
        "function inRange(iso){var d=new Date(iso||0);if(isNaN(d.getTime()))return false;var f=window.reportDateFrom?new Date(window.reportDateFrom):null,t=window.reportDateTo?new Date(window.reportDateTo):null;return (!f||isNaN(f.getTime())||d>=f)&&(!t||isNaN(t.getTime())||d<=t);}" +
        "window.mfixExportReportsCsv=function(){var sales=(window.STATE.sales||[]).filter(function(s){return inRange(s.createdAt||s.date||s.at);});var rows=[['תאריך','מספר מסמך','לקוח','טלפון','סה\"כ','שולם','עודף','אמצעי תשלום','סטטוס']];sales.forEach(function(s){var pays=(s.payments||s.paymentRows||[]).map(function(p){return p.method||p.type||'';}).join(' + ');rows.push([s.createdAt||s.date||s.at||'',s.number||s.docNumber||s.id||'',s.customerName||'',s.customerPhone||'',Number(s.totalIncl||s.total||0).toFixed(2),Number(s.paid||s.amountPaid||0).toFixed(2),Number(s.change||0).toFixed(2),pays,s.status||'completed']);});var csv='\\uFEFF'+rows.map(function(r){return r.map(escCsv).join(',');}).join('\\r\\n');var blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='MFIX-report-'+new Date().toISOString().slice(0,10)+'.csv';document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},1000);if(window.toast)window.toast('הדוח יוצא כקובץ CSV ('+sales.length+' מכירות)','ok');};" +
        "var original=window.renderReports;window.renderReports=function(){var r=original.apply(this,arguments);setTimeout(function(){var v=document.getElementById('view-reports');if(!v||v.querySelector('.mfix-report-export'))return;var b=document.createElement('button');b.type='button';b.className='btn btn-outline mfix-report-export';b.textContent='⬇️ ייצוא CSV';b.style.marginBottom='10px';b.onclick=window.mfixExportReportsCsv;v.insertBefore(b,v.firstChild);},0);return r;};window.renderReports();" +
        "}" +
        "function loadHolds(){try{return JSON.parse(localStorage.getItem('mfix_pos_held_sales_v1')||'[]');}catch(e){return [];}}" +
        "function saveHolds(h){localStorage.setItem('mfix_pos_held_sales_v1',JSON.stringify(h.slice(0,20)));}" +
        "function renderHolds(){var box=document.getElementById('mfixHeldSalesList');if(!box)return;var h=loadHolds();if(!h.length){box.innerHTML='<div class=\"muted\">אין מכירות מושהות</div>';return;}box.innerHTML=h.map(function(x,i){return '<div class=\"card\" style=\"margin-top:8px;padding:10px\"><b>'+String(x.label||('מכירה '+(i+1))).replace(/[<>]/g,'')+'</b><div class=\"muted\">'+(x.cart||[]).length+' פריטים · ₪'+Number(x.total||0).toFixed(2)+' · '+new Date(x.at||Date.now()).toLocaleString('he-IL')+'</div><div style=\"margin-top:8px;display:flex;gap:6px\"><button class=\"btn btn-primary mfix-resume\" data-i=\"'+i+'\">המשך מכירה</button><button class=\"btn btn-ghost mfix-delete-hold\" data-i=\"'+i+'\">מחק</button></div></div>';}).join('');box.querySelectorAll('.mfix-resume').forEach(function(b){b.onclick=function(){var h=loadHolds(),x=h[Number(b.dataset.i)];if(!x)return;if((window.STATE.cart||[]).length&&window.confirm&&!confirm('הסל הנוכחי יוחלף במכירה המושהית. להמשיך?'))return;window.STATE.cart=Array.isArray(x.cart)?x.cart:[];window.STATE.cartCustomerId=x.cartCustomerId||null;window.STATE.docCustomerName=x.docCustomerName||'';window.STATE.docCustomerPhone=x.docCustomerPhone||'';h.splice(Number(b.dataset.i),1);saveHolds(h);if(typeof window.render==='function')window.render();renderHolds();if(window.toast)window.toast('המכירה הוחזרה לסל','ok');};});box.querySelectorAll('.mfix-delete-hold').forEach(function(b){b.onclick=function(){var h=loadHolds();h.splice(Number(b.dataset.i),1);saveHolds(h);renderHolds();};});}" +
        "function installPosControls(){var v=document.getElementById('view-pos');if(!v)return false;if(v.querySelector('.mfix-pos-controls'))return true;var wrap=document.createElement('div');wrap.className='card mfix-pos-controls';wrap.style.marginBottom='12px';wrap.innerHTML='<div class=\"section-title\">🛒 שליטה במכירה</div><div style=\"display:flex;gap:8px;flex-wrap:wrap\"><button type=\"button\" class=\"btn btn-amber\" id=\"mfixHoldSale\">⏸️ השהה מכירה</button><button type=\"button\" class=\"btn btn-ghost\" id=\"mfixShowHolds\">📋 מכירות מושהות</button><button type=\"button\" class=\"btn btn-red\" id=\"mfixClearSale\">🗑️ נקה סל</button></div><div id=\"mfixHeldSalesList\" style=\"display:none;margin-top:8px\"></div>';v.insertBefore(wrap,v.firstChild);wrap.querySelector('#mfixHoldSale').onclick=function(){var cart=Array.isArray(window.STATE.cart)?window.STATE.cart:[];if(!cart.length){if(window.toast)window.toast('הסל ריק — אין מה להשהות','err');return;}var total=0;cart.forEach(function(x){total+=Number(x.lineTotal||x.total||((Number(x.price)||0)*(Number(x.qty)||1))||0);});var label=window.prompt?prompt('שם למכירה המושהית (אופציונלי):','מכירה '+new Date().toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'})):'';var h=loadHolds();h.unshift({id:'hold_'+Date.now(),label:label||'מכירה מושהית',cart:JSON.parse(JSON.stringify(cart)),cartCustomerId:window.STATE.cartCustomerId||null,docCustomerName:window.STATE.docCustomerName||'',docCustomerPhone:window.STATE.docCustomerPhone||'',total:total,at:new Date().toISOString()});saveHolds(h);window.STATE.cart=[];window.STATE.cartCustomerId=null;window.STATE.docCustomerName='';window.STATE.docCustomerPhone='';if(typeof window.render==='function')window.render();if(window.toast)window.toast('המכירה הושהתה ונשמרה','ok');};wrap.querySelector('#mfixShowHolds').onclick=function(){var list=wrap.querySelector('#mfixHeldSalesList');list.style.display=list.style.display==='none'?'block':'none';if(list.style.display==='block')renderHolds();};wrap.querySelector('#mfixClearSale').onclick=function(){var cart=Array.isArray(window.STATE.cart)?window.STATE.cart:[];if(!cart.length){if(window.toast)window.toast('הסל כבר ריק','ok');return;}if(window.confirm&&!confirm('לנקות את כל הפריטים מהסל?'))return;window.STATE.cart=[];window.STATE.cartCustomerId=null;window.STATE.docCustomerName='';window.STATE.docCustomerPhone='';if(typeof window.render==='function')window.render();if(window.toast)window.toast('הסל נוקה','ok');};return true;}" +
        "installReports();var tries=0,timer=setInterval(function(){if(installPosControls()||tries++>=40)clearInterval(timer);},500);console.log('[MFIX] reports export + POS hold/resume controls active');" +
        "})();";

    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        View root = ((ViewGroup) findViewById(android.R.id.content)).getChildAt(0);
        if (root instanceof WebView) {
            ((WebView) root).postDelayed(() -> ((WebView) root).evaluateJavascript(PATCH, null), 1000);
        }
    }
}
