package com.mfix.pos;

import android.webkit.WebView;

/** Adds manager-only creation and editing for the local POS user directory. */
public final class UserManagementPatchActivity {
    private UserManagementPatchActivity() {}

    private static final String PATCH =
        "(function(){if(window.__mfixUserManagementPatch)return;window.__mfixUserManagementPatch=true;"+
        "var KEY='mfix_users_v2',TABS=['pos','inventory','customers','repairs','reports','settings'];"+
        "function read(){try{var a=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(a)?a:[]}catch(e){return [];}}"+
        "function write(a){localStorage.setItem(KEY,JSON.stringify(a));}"+
        "function esc(s){return String(s==null?'':s).replace(/[&<>\\\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;',\"'\":'&#39;'}[c];});}"+
        "function tabLabel(t){return {pos:'קופה',inventory:'מלאי',customers:'לקוחות',repairs:'תיקונים',reports:'דוחות',settings:'הגדרות'}[t]||t;}"+
        "function openEditor(index){var a=read(),u=index<0?{id:'u_'+Date.now(),name:'',role:'cashier',active:true,permissions:{}}:a[index];if(!u)return;var p=u.permissions||{};var html='<div class=\\\"modal wide\\\"><div class=\\\"modal-head\\\"><h3>'+ (index<0?'➕ משתמש חדש':'✏️ עריכת משתמש') +'</h3><button class=\\\"modal-close\\\" onclick=\\\"closeModal()\\\">×</button></div><div class=\\\"modal-body\\\"><div class=\\\"grid2\\\"><div class=\\\"field\\\"><label class=\\\"flabel\\\">שם משתמש</label><input id=\\\"mfixUserName\\\" class=\\\"input\\\" maxlength=\\\"60\\\" value=\\\"'+esc(u.name||'')+'\\\"></div><div class=\\\"field\\\"><label class=\\\"flabel\\\">תפקיד</label><select id=\\\"mfixUserRole\\\" class=\\\"input\\\"><option value=\\\"cashier\\\" '+(u.role==='cashier'?'selected':'')+'>קופאי</option><option value=\\\"manager\\\" '+(u.role==='manager'?'selected':'')+'>מנהל</option></select></div></div><div class=\\\"muted\\\" style=\\\"font-size:12px;margin:8px 0\\\">למנהל יש גישה מלאה. הרשאות המסכים רלוונטיות לקופאי.</div><div id=\\\"mfixUserPerms\\\" style=\\\"display:flex;gap:6px;flex-wrap:wrap\\\">'+TABS.map(function(t){var on=u.role==='manager'||p[t]!==false;return '<label class=\\\"btn '+(on?'btn-primary':'btn-ghost')+'\\\" style=\\\"cursor:pointer\\\"><input type=\\\"checkbox\\\" data-perm=\\\"'+t+'\\\" '+(on?'checked':'')+' style=\\\"margin-inline-end:5px\\\">'+tabLabel(t)+'</label>';}).join('')+'</div></div><div class=\\\"modal-foot\\\"><button class=\\\"btn btn-ghost\\\" onclick=\\\"closeModal()\\\">ביטול</button><button class=\\\"btn btn-primary\\\" id=\\\"mfixUserSave\\\">שמור משתמש</button></div></div>';openModal(html,{wide:true});setTimeout(function(){var role=document.getElementById('mfixUserRole'),perms=document.querySelectorAll('[data-perm]');function sync(){var manager=role.value==='manager';perms.forEach(function(x){x.disabled=manager;if(manager)x.checked=true;});}role.onchange=sync;sync();document.getElementById('mfixUserSave').onclick=function(){var name=document.getElementById('mfixUserName').value.trim(),r=role.value;if(!name){toast('יש להזין שם משתמש','err');return;}var users=read();var duplicate=users.some(function(x,i){return i!==index&&String(x.name||'').trim().toLowerCase()===name.toLowerCase();});if(duplicate){toast('שם המשתמש כבר קיים','err');return;}if(index<0){u.createdAt=new Date().toISOString();}u.name=name;u.role=r;u.active=u.active!==false;u.permissions=u.permissions||{};TABS.forEach(function(t){u.permissions[t]=r==='manager'||!!document.querySelector('[data-perm=\\\"'+t+'\\\"]')?.checked;});if(index<0)users.push(u);else users[index]=u;write(users);closeModal();toast(index<0?'המשתמש נוצר':'המשתמש עודכן','ok');draw();};},0);}"+
        "function draw(){var v=document.getElementById('view-settings');if(!v)return false;if(STATE.currentRole!=='manager')return true;var old=document.getElementById('mfixUserManagementCard');if(old)old.remove();var b=document.createElement('div');b.id='mfixUserManagementCard';b.className='card';b.style.marginBottom='12px';var a=read();b.innerHTML='<div class=\\\"section-title\\\">👥 ניהול משתמשים</div><div class=\\\"muted\\\" style=\\\"font-size:12px;margin-bottom:10px\\\">יצירה ועריכה של משתמשים והרשאות מסכים. שינוי הרשאות משפיע על הגישה המקומית לקופה.</div><div id=\\\"mfixUserMgmtRows\\\"></div><button id=\\\"mfixAddUser\\\" class=\\\"btn btn-primary\\\" type=\\\"button\\\" style=\\\"margin-top:8px\\\">➕ הוסף משתמש</button>';v.insertBefore(b,v.firstChild);var rows=b.querySelector('#mfixUserMgmtRows');rows.innerHTML=a.length?a.map(function(u,i){return '<div class=\\\"card\\\" style=\\\"background:var(--gray-50);margin-bottom:8px\\\"><div style=\\\"display:flex;align-items:center;justify-content:space-between;gap:8px\\\"><div><b>'+esc(u.name||'משתמש')+'</b><div class=\\\"muted\\\" style=\\\"font-size:11px;margin-top:3px\\\">'+(u.role==='manager'?'מנהל':'קופאי')+' · '+(u.active===false?'מושבת':'פעיל')+'</div></div><button type=\\\"button\\\" class=\\\"btn btn-outline\\\" data-edit-user=\\\"'+i+'\\\">✏️ ערוך</button></div></div>';}).join(''):'<div class=\\\"empty-state\\\" style=\\\"padding:12px\\\">אין משתמשים.</div>';b.querySelectorAll('[data-edit-user]').forEach(function(x){x.onclick=function(){openEditor(Number(x.dataset.editUser));};});document.getElementById('mfixAddUser').onclick=function(){openEditor(-1);};return true;}"+
        "var tries=0;function loop(){tries++;try{if(draw()||tries>=40)clearTimeout(window.__mfixUserTimer);}catch(e){console.error('[MFIX USERS]',e);}if(tries<40)window.__mfixUserTimer=setTimeout(loop,700);}loop();})();";

    public static void install(WebView webView) {
        if (webView == null) return;
        webView.postDelayed(() -> webView.evaluateJavascript(PATCH, null), 3600);
    }
}
