package com.mfix.pos;

import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;

/** Runtime user/permission layer with per-user capabilities. */
public class UsersPermissionsPatchActivity extends YeshInvoicePatchActivity {
    private static final String USERS_PATCH =
        "(function(){"+
        "if(window.__mfixUsersPatchV2)return;window.__mfixUsersPatchV2=true;"+
        "var KEY='mfix_pos_users_v1',ROLE_KEY='mfix_pos_active_user_v1';"+
        "var ALL=['inventory','inventoryEdit','returns','discounts','reports','settings','backup','yesh','users'];"+
        "function load(){try{var u=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(u)?u:[];}catch(e){return [];}}"+
        "function save(v){localStorage.setItem(KEY,JSON.stringify(v));}"+
        "function defaults(role){var p={inventory:true,inventoryEdit:false,returns:false,discounts:false,reports:false,settings:false,backup:false,yesh:false,users:false};if(role==='manager')ALL.forEach(function(k){p[k]=true;});return p;}"+
        "function users(){var u=load();if(!u.length){u=[{id:'manager',name:'מנהל',role:'manager',pin:'1234',active:true,permissions:defaults('manager')}];save(u);}var changed=false;u.forEach(function(x){if(!x.permissions){x.permissions=defaults(x.role);changed=true;}else{var d=defaults(x.role);ALL.forEach(function(k){if(typeof x.permissions[k]!=='boolean')x.permissions[k]=d[k];});}});if(changed)save(u);return u;}"+
        "function active(){var u=users(),id=localStorage.getItem(ROLE_KEY)||'manager';return u.find(function(x){return x.id===id&&x.active!==false;})||u[0];}"+
        "function isManager(){return active().role==='manager'||active().permissions.users===true&&active().permissions.settings===true;}"+
        "function allowed(k){var x=active();if(x.role==='manager')return true;return !!(x.permissions&&x.permissions[k]);}"+
        "function validPin(p){return /^[0-9]{4,8}$/.test(String(p||''));}"+
        "function label(k){return {inventory:'צפייה במלאי',inventoryEdit:'עריכת מוצרים ומלאי',returns:'החזרות וזיכויים',discounts:'הנחות ידניות',reports:'דוחות',settings:'הגדרות מערכת',backup:'גיבוי ושחזור',yesh:'יש חשבונית',users:'ניהול משתמשים'}[k]||k;}"+
        "function ensureState(){if(window.STATE){STATE.currentRole=active().role;window.__mfixUserPermissions=active().permissions||defaults(active().role);}}"+
        "window.mfixUserAllowed=allowed;"+
        "window.mfixOpenUsers=function(){if(!allowed('users')){toast('אין הרשאה לניהול משתמשים','err');return;}var u=users();var rows=u.map(function(x){var canEdit=active().role==='manager'||x.id===active().id;var perms=x.permissions||defaults(x.role);var checks=ALL.map(function(k){return '<label style=\\\"display:flex;gap:6px;align-items:center;font-size:12px;margin:3px 0;\\\"><input type=\\\"checkbox\\\" data-user-perm=\\\"'+k+'\\\" '+(perms[k]?'checked':'')+' '+(canEdit?'':'disabled')+'> '+label(k)+'</label>';}).join('');return '<tr><td><b>'+x.name+'</b></td><td>'+({manager:'מנהל',cashier:'קופאי'}[x.role]||x.role)+'</td><td>'+(x.active===false?'לא פעיל':'פעיל')+'</td><td><button class=\\\"btn btn-ghost\\\" onclick=\\\"mfixLoginUser(\\\''+x.id+'\\\')\\\">החלף</button> <button class=\\\"btn btn-ghost\\\" onclick=\\\"mfixChangeUserPin(\\\''+x.id+'\\\')\\\">PIN</button> '+(x.id==='manager'?'':'<button class=\\\"btn btn-red\\\" onclick=\\\"mfixToggleUser(\\\''+x.id+'\\\')\\\">'+(x.active===false?'הפעל':'השבת')+'</button>')+'</td></tr><tr><td colspan=\\\"4\\\" style=\\\"background:var(--gray-50);padding:8px 12px;\\\"><b style=\\\"font-size:12px;\\\">הרשאות — '+x.name+'</b>'+checks+(canEdit?'<button class=\\\"btn btn-primary\\\" style=\\\"margin-top:6px;padding:6px 10px;font-size:12px;\\\" onclick=\\\"mfixSaveUserPermissions(\\\''+x.id+'\\\')\\\">שמור הרשאות</button>':'')+'</td></tr>';}).join('');var html='<div class=\\\"modal wide\\\"><div class=\\\"modal-head\\\"><h3>👥 משתמשים והרשאות</h3><button class=\\\"modal-close\\\" onclick=\\\"closeModal()\\\">✕</button></div><div class=\\\"modal-body\\\"><div class=\\\"card\\\" style=\\\"margin-bottom:14px\\\"><b>משתמש פעיל: '+active().name+'</b><div class=\\\"muted\\\">הרשאת '+(active().role==='manager'?'מנהל מלא':'קופאי עם הרשאות מותאמות')+'</div></div><table class=\\\"tbl\\\"><thead><tr><th>שם</th><th>תפקיד</th><th>סטטוס</th><th>פעולות</th></tr></thead><tbody>'+rows+'</tbody></table><hr><div class=\\\"grid3\\\"><input id=\\\"mfixUserName\\\" class=\\\"input\\\" placeholder=\\\"שם משתמש\\\"><select id=\\\"mfixUserRole\\\" class=\\\"input\\\"><option value=\\\"cashier\\\">קופאי</option><option value=\\\"manager\\\">מנהל</option></select><input id=\\\"mfixUserPin\\\" class=\\\"input\\\" type=\\\"password\\\" inputmode=\\\"numeric\\\" placeholder=\\\"PIN 4–8 ספרות\\\"></div></div><div class=\\\"modal-foot\\\"><button class=\\\"btn btn-primary\\\" onclick=\\\"mfixAddUser()\\\">הוסף משתמש</button></div></div>';openModal(html,{wide:true});};"+
        "window.mfixAddUser=function(){if(!allowed('users')){toast('אין הרשאה לניהול משתמשים','err');return;}var n=document.getElementById('mfixUserName').value.trim(),r=document.getElementById('mfixUserRole').value,p=document.getElementById('mfixUserPin').value;if(!n||!validPin(p)){toast('יש להזין שם ו-PIN בן 4–8 ספרות','err');return;}var u=users();u.push({id:'u_'+Date.now(),name:n,role:r,pin:p,active:true,permissions:defaults(r)});save(u);mfixOpenUsers();toast('המשתמש נוסף','ok');};"+
        "window.mfixSaveUserPermissions=function(id){if(!allowed('users')){toast('אין הרשאה','err');return;}var u=users(),x=u.find(function(v){return v.id===id;});if(!x)return;if(x.id==='manager'&&active().id!=='manager'){toast('רק מנהל יכול לשנות הרשאות של מנהל ראשי','err');return;}var p=x.permissions||defaults(x.role);ALL.forEach(function(k){var el=document.querySelector('[data-user-perm=\\\"'+k+'\\\"]');if(el&&(!el.disabled||x.id===active().id))p[k]=!!el.checked;});if(x.role==='manager')ALL.forEach(function(k){p[k]=true;});x.permissions=p;save(u);ensureState();mfixOpenUsers();toast('הרשאות המשתמש נשמרו','ok');};"+
        "window.mfixToggleUser=function(id){if(!allowed('users')){toast('אין הרשאה','err');return;}var u=users();u.forEach(function(x){if(x.id===id&&x.id!=='manager')x.active=!x.active;});save(u);mfixOpenUsers();};"+
        "window.mfixChangeUserPin=function(id){var x=users().find(function(v){return v.id===id;});if(!x)return;if(x.id!==active().id&&!allowed('users')){toast('אין הרשאה לשנות PIN של משתמש אחר','err');return;}var p=prompt('הזן PIN חדש עבור '+x.name+' (4–8 ספרות)');if(p===null)return;if(!validPin(p)){toast('PIN חייב להכיל 4–8 ספרות בלבד','err');return;}x.pin=p;save(users());toast('ה-PIN עודכן','ok');if(x.id===active().id)mfixOpenUsers();};"+
        "window.mfixLoginUser=function(id){var x=users().find(function(v){return v.id===id&&v.active!==false;});if(!x)return;var pin=prompt('הזן PIN עבור '+x.name);if(pin===x.pin){localStorage.setItem(ROLE_KEY,x.id);ensureState();toast('נכנסת כ-'+x.name,'ok');closeModal();apply();}else if(pin!==null)toast('PIN שגוי','err');};"+
        "function wrapFunction(name,perm){if(typeof window[name]!=='function'||window[name].__mfixPermWrapped)return;var original=window[name];var wrapped=function(){if(!allowed(perm)){toast('הפעולה דורשת הרשאה: '+label(perm),'err');return;}return original.apply(this,arguments);};wrapped.__mfixPermWrapped=true;window[name]=wrapped;}"+
        "function patchPermissions(){ensureState();if(window.STATE){window.__mfixOriginalCanManage=window.__mfixOriginalCanManage||window.canManage;window.canManage=function(){return allowed('inventoryEdit')||active().role==='manager';};window.__mfixOriginalTabAllowed=window.__mfixOriginalTabAllowed||window.tabAllowed;window.tabAllowed=function(id){if(id==='reports')return allowed('reports');if(id==='settings')return allowed('settings');if(id==='inventory')return allowed('inventory');return true;};}wrapFunction('openCartDiscountModal','discounts');wrapFunction('applyCartDiscount','discounts');wrapFunction('processReturn','returns');wrapFunction('exportBackup','backup');wrapFunction('importBackup','backup');wrapFunction('saveYeshInvoiceSettings','yesh');wrapFunction('testYeshInvoiceConnection','yesh');}"+
        "function protectedArea(el){var t=(el.textContent||'')+' '+(el.getAttribute&&el.getAttribute('onclick')||'');return /הגדר|דוח|report|settings/i.test(t);}"+
        "document.addEventListener('click',function(e){ensureState();if(active().role==='manager')return;var n=e.target.closest('button,.navtab,a');if(n&&protectedArea(n)&&!allowed(n.textContent&&n.textContent.indexOf('דוח')>=0?'reports':'settings')){e.preventDefault();e.stopImmediatePropagation();toast('פעולה זו זמינה רק לפי הרשאת המשתמש','err');}},true);"+
        "function apply(){ensureState();var host=document.querySelector('.topbar-right');if(host&&!document.getElementById('mfixUsersButton')){var b=document.createElement('button');b.id='mfixUsersButton';b.className='btn btn-outline';b.textContent='👤 '+active().name;b.onclick=function(){if(allowed('users'))mfixOpenUsers();else mfixLoginUser('manager');};host.insertBefore(b,host.firstChild);}else{var b=document.getElementById('mfixUsersButton');if(b)b.textContent='👤 '+active().name;}patchPermissions();}"+
        "users();apply();setInterval(apply,1000);console.log('[MFIX] users and granular permissions patch active');"+
        "})();";

    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        View root = ((ViewGroup) findViewById(android.R.id.content)).getChildAt(0);
        if (root instanceof WebView) {
            ((WebView) root).postDelayed(() -> ((WebView) root).evaluateJavascript(USERS_PATCH, null), 1500);
        }
    }
}
