package com.mfix.pos;

import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;

/** Runtime integration layer for Yesh Invoice. Provider submission remains disabled until a verified API contract is configured. */
public class YeshInvoicePatchActivity extends BackupRestorePatchActivity {
    private static final String PATCH =
        "(function(){if(window.__mfixYeshInvoicePatch)return;window.__mfixYeshInvoicePatch=true;"+
        "var KEY='mfix_yesh_invoice_v1',OUTBOX='mfix_yesh_invoice_outbox_v1';"+
        "function cfg(){try{return Object.assign({enabled:false,endpoint:'',apiKey:'',autoSync:false},JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){return {enabled:false,endpoint:'',apiKey:'',autoSync:false};}}"+
        "function save(v){localStorage.setItem(KEY,JSON.stringify(v));}"+
        "function outbox(){try{return JSON.parse(localStorage.getItem(OUTBOX)||'[]');}catch(e){return [];}}"+
        "function saveOutbox(v){localStorage.setItem(OUTBOX,JSON.stringify(v));}"+
        "function queueSale(s){if(!s||!s.id)return;var q=outbox();if(q.some(function(x){return x.saleId===s.id;}))return;q.push({saleId:s.id,number:s.number||'',docType:s.docType||'',queuedAt:new Date().toISOString(),payload:s});saveOutbox(q);toast('המסמך נוסף לתור יש חשבונית ('+q.length+')','ok');}"+
        "function fixInventoryFileInput(){var el=document.getElementById('inventoryImportFile');if(!el)return false;el.accept='.csv,.tsv,.txt,.xlsx,.xls,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv,text/plain';el.style.display='block';el.style.position='fixed';el.style.left='0';el.style.top='0';el.style.width='1px';el.style.height='1px';el.style.opacity='0.01';el.style.zIndex='-1';el.setAttribute('aria-hidden','true');return true;}"+
        "function hookInventoryImport(){var el=document.getElementById('inventoryImportFile');if(!el)return false;fixInventoryFileInput();window.openInventoryImport=function(){var f=document.getElementById('inventoryImportFile');if(!f){toast('בחירת קובץ מלאי אינה זמינה','err');return;}fixInventoryFileInput();try{f.focus();f.click();}catch(e){toast('לא ניתן לפתוח בחירת קובץ מלאי: '+(e&&e.message?e.message:'שגיאה'),'err');}};if(!el.__mfixInventoryHook){el.addEventListener('change',function(){if(this.files&&this.files[0]&&typeof window.handleInventoryImportFile==='function'){window.handleInventoryImportFile(this.files[0]);}this.value='';});el.__mfixInventoryHook=true;}return true;}"+
        "window.mfixOpenYeshInvoiceSettings=function(){var c=cfg(),q=outbox();var html='<div class=\\\"modal wide\\\"><div class=\\\"modal-head\\\"><h3>🧾 יש חשבונית — אינטגרציה</h3><button class=\\\"modal-close\\\" onclick=\\\"closeModal()\\\">✕</button></div><div class=\\\"modal-body\\\"><div class=\\\"card\\\"><div class=\\\"field\\\"><label class=\\\"flabel\\\"><input id=\\\"yiEnabled\\\" type=\\\"checkbox\\\" '+(c.enabled?'checked':'')+'> הפעל אינטגרציה</label></div><div class=\\\"field\\\"><label class=\\\"flabel\\\">כתובת Endpoint</label><input id=\\\"yiEndpoint\\\" class=\\\"input\\\" style=\\\"direction:ltr\\\" value=\\\"'+esc(c.endpoint||'')+'\\\" placeholder=\\\"https://...\\\"></div><div class=\\\"field\\\"><label class=\\\"flabel\\\">API Key / Token</label><input id=\\\"yiApiKey\\\" class=\\\"input\\\" type=\\\"password\\\" style=\\\"direction:ltr\\\" value=\\\"'+esc(c.apiKey||'')+'\\\" placeholder=\\\"Token\\\"></div><label class=\\\"flabel\\\"><input id=\\\"yiAuto\\\" type=\\\"checkbox\\\" '+(c.autoSync?'checked':'')+'> הוסף מכירות לתור אוטומטי לאחר מכירה</label><div class=\\\"muted\\\" style=\\\"margin-top:10px\\\">בתור ממתינים כרגע '+q.length+' מסמכים. שליחה אמיתית תופעל רק לאחר API מאומת.</div></div></div><div class=\\\"modal-foot\\\"><button class=\\\"btn btn-outline\\\" onclick=\\\"mfixOpenYeshInvoiceOutbox()\\\">נהל תור ('+q.length+')</button><button class=\\\"btn btn-outline\\\" onclick=\\\"mfixYeshInvoiceTest()\\\">בדיקת חיבור</button><button class=\\\"btn btn-primary\\\" onclick=\\\"mfixSaveYeshInvoice()\\\">שמור</button></div></div>';openModal(html,{wide:true});};"+
        "window.mfixOpenYeshInvoiceOutbox=function(){var q=outbox();var rows=q.length?q.map(function(x,i){var d=x.queuedAt?new Date(x.queuedAt).toLocaleString('he-IL'):'';return '<div class=\\\"card\\\" style=\\\"margin-bottom:8px\\\"><b>#'+esc(String(x.number||''))+'</b> · '+esc(String(x.docType||''))+'<div class=\\\"muted\\\">'+esc(d)+'</div><button class=\\\"btn btn-ghost\\\" style=\\\"margin-top:6px\\\" onclick=\\\"mfixDeleteYeshInvoiceOutbox('+i+')\\\">הסר מהתור</button></div>';}).join(''):'<div class=\\\"empty\\\">אין מסמכים ממתינים</div>';var html='<div class=\\\"modal wide\\\"><div class=\\\"modal-head\\\"><h3>🧾 תור יש חשבונית</h3><button class=\\\"modal-close\\\" onclick=\\\"closeModal()\\\">✕</button></div><div class=\\\"modal-body\\\"><div class=\\\"muted\\\" style=\\\"margin-bottom:10px\\\">שליחה לספק עדיין מושבתת עד להגדרת API מאומת.</div>'+rows+'</div><div class=\\\"modal-foot\\\"><button class=\\\"btn btn-danger\\\" '+(q.length?'':'disabled')+' onclick=\\\"mfixClearYeshInvoiceOutbox()\\\">נקה תור</button><button class=\\\"btn btn-outline\\\" onclick=\\\"mfixOpenYeshInvoiceSettings()\\\">חזור להגדרות</button></div></div>';openModal(html,{wide:true});};"+
        "window.mfixDeleteYeshInvoiceOutbox=function(i){var q=outbox();if(i<0||i>=q.length)return;if(!confirm('להסיר מסמך זה מתור יש חשבונית?'))return;q.splice(i,1);saveOutbox(q);toast('המסמך הוסר מהתור','ok');mfixOpenYeshInvoiceOutbox();};"+
        "window.mfixClearYeshInvoiceOutbox=function(){if(!confirm('לנקות את כל תור יש חשבונית?'))return;saveOutbox([]);toast('התור נוקה','ok');mfixOpenYeshInvoiceOutbox();};"+
        "window.mfixSaveYeshInvoice=function(){var v={enabled:document.getElementById('yiEnabled').checked,endpoint:document.getElementById('yiEndpoint').value.trim(),apiKey:document.getElementById('yiApiKey').value.trim(),autoSync:document.getElementById('yiAuto').checked};if(v.enabled&&!/^https:\\/\\//i.test(v.endpoint)){toast('יש להזין Endpoint מאובטח מסוג HTTPS','err');return;}save(v);toast('הגדרות יש חשבונית נשמרו','ok');closeModal();};"+
        "window.mfixYeshInvoiceTest=async function(){var c=cfg(),ep=document.getElementById('yiEndpoint'),key=document.getElementById('yiApiKey');if(ep)c.endpoint=ep.value.trim();if(key)c.apiKey=key.value.trim();if(!/^https:\\/\\//i.test(c.endpoint)){toast('יש להזין Endpoint HTTPS לבדיקת חיבור','err');return;}try{var r=await fetch(c.endpoint,{method:'OPTIONS',headers:c.apiKey?{'Authorization':'Bearer '+c.apiKey}:{}});toast(r.ok||r.status===405?'ה־Endpoint הגיב ('+r.status+')':'ה־Endpoint החזיר '+r.status,r.ok||r.status===405?'ok':'err');}catch(e){toast('לא ניתן להתחבר ל־Endpoint: '+(e&&e.message?e.message:'שגיאה'),'err');}};"+
        "function hookCheckout(){if(window.__mfixYeshCheckoutHook||typeof window.finalizeSale!=='function')return false;var old=window.finalizeSale;window.finalizeSale=async function(){var before=(window.STATE&&Array.isArray(STATE.sales)?STATE.sales.length:0);var result=await old.apply(this,arguments);var c=cfg();if(c.enabled&&c.autoSync&&window.STATE&&Array.isArray(STATE.sales)&&STATE.sales.length>before)queueSale(STATE.sales[STATE.sales.length-1]);return result;};window.__mfixYeshCheckoutHook=true;return true;}"+
        "function inject(){hookInventoryImport();var host=document.querySelector('.topbar-right');if(host&&!document.getElementById('mfixYeshInvoiceButton')){var b=document.createElement('button');b.id='mfixYeshInvoiceButton';b.className='btn btn-outline';b.textContent='🧾 יש חשבונית';b.onclick=window.mfixOpenYeshInvoiceSettings;host.appendChild(b);}hookCheckout();}inject();setInterval(inject,1000);console.log('[MFIX] Yesh Invoice + inventory import patch active');}"+
        "install();})();";

    @Override protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        View root=((ViewGroup)findViewById(android.R.id.content)).getChildAt(0);
        if(root instanceof WebView)((WebView)root).postDelayed(()->((WebView)root).evaluateJavascript(PATCH,null),2100);
    }
}
