plugins { id 'com.android.application' }

android {
    namespace 'com.mfix.pos'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mfix.pos'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
